const qwertyLayout = [
  [
    { val: "`", display: "`", secondary: "~", size: 1, code: "Backquote" },
    { val: "1", display: "1", secondary: "!", size: 1, code: "Digit1" },
    { val: "2", display: "2", secondary: "@", size: 1, code: "Digit2" },
    { val: "3", display: "3", secondary: "#", size: 1, code: "Digit3" },
    { val: "4", display: "4", secondary: "$", size: 1, code: "Digit4" },
    { val: "5", display: "5", secondary: "%", size: 1, code: "Digit5" },
    { val: "6", display: "6", secondary: "^", size: 1, code: "Digit6" },
    { val: "7", display: "7", secondary: "&", size: 1, code: "Digit7" },
    { val: "8", display: "8", secondary: "*", size: 1, code: "Digit8" },
    { val: "9", display: "9", secondary: "(", size: 1, code: "Digit9" },
    { val: "0", display: "0", secondary: ")", size: 1, code: "Digit0" },
    { val: "-", display: "-", secondary: "_", size: 1, code: "Minus" },
    { val: "=", display: "=", secondary: "+", size: 1, code: "Equal" },
    { val: "Backspace", display: "Backspace", size: 2, code: "Backspace" },
  ],
  [
    { val: "Tab", display: "", size: 1.5, code: "" },
    { val: "q", display: "Q", size: 1, code: "KeyQ" },
    { val: "w", display: "W", size: 1, code: "KeyW" },
    { val: "e", display: "E", size: 1, code: "KeyE" },
    { val: "r", display: "R", size: 1, code: "KeyR" },
    { val: "t", display: "T", size: 1, code: "KeyT" },
    { val: "y", display: "Y", size: 1, code: "KeyY" },
    { val: "u", display: "U", size: 1, code: "KeyU" },
    { val: "i", display: "I", size: 1, code: "KeyI" },
    { val: "o", display: "O", size: 1, code: "KeyO" },
    { val: "p", display: "P", size: 1, code: "KeyP" },
    { val: "[", display: "[", secondary: "{", size: 1, code: "BracketLeft" },
    { val: "]", display: "]", secondary: "}", size: 1, code: "BracketRight" },
    { val: "\\", display: "\\", secondary: "|", size: 1.5, code: "Backslash" },
  ],
  [
    { val: "CapsLock", display: "Caps", size: 1.75, code: "CapsLock" },
    { val: "a", display: "A", size: 1, code: "KeyA" },
    { val: "s", display: "S", size: 1, code: "KeyS" },
    { val: "d", display: "D", size: 1, code: "KeyD" },
    { val: "f", display: "F", size: 1, code: "KeyF" },
    { val: "g", display: "G", size: 1, code: "KeyG" },
    { val: "h", display: "H", size: 1, code: "KeyH" },
    { val: "j", display: "J", size: 1, code: "KeyJ" },
    { val: "k", display: "K", size: 1, code: "KeyK" },
    { val: "l", display: "L", size: 1, code: "KeyL" },
    { val: ";", display: ";", secondary: ":", size: 1, code: "Semicolon" },
    { val: "'", display: "'", secondary: '"', size: 1, code: "Quote" },
    { val: "Enter", display: "Enter", size: 2.25, code: "Enter" },
  ],
  [
    { val: "ShiftLeft", display: "Shift", size: 2.25, code: "ShiftLeft" },
    { val: "z", display: "Z", size: 1, code: "KeyZ" },
    { val: "x", display: "X", size: 1, code: "KeyX" },
    { val: "c", display: "C", size: 1, code: "KeyC" },
    { val: "v", display: "V", size: 1, code: "KeyV" },
    { val: "b", display: "B", size: 1, code: "KeyB" },
    { val: "n", display: "N", size: 1, code: "KeyN" },
    { val: "m", display: "M", size: 1, code: "KeyM" },
    { val: ",", display: ",", secondary: "<", size: 1, code: "Comma" },
    { val: ".", display: ".", secondary: ">", size: 1, code: "Period" },
    { val: "/", display: "/", secondary: "?", size: 1, code: "Slash" },
    { val: "ShiftRight", display: "Shift", size: 2.75, code: "ShiftRight" },
  ],
  [
    { val: "ControlLeft", display: "", size: 1.25, code: "" },
    { val: "MetaLeft", display: "", size: 1.25, code: "" },
    { val: "AltLeft", display: "", size: 1.25, code: "" },
    { val: " ", display: "Space", size: 6.25, code: "Space" },
    { val: "AltRight", display: "", size: 1.25, code: "" },
    { val: "Fn", display: "", size: 1.25, code: "Fn" },
    { val: "ContextMenu", display: "", size: 1.25, code: "" },
    { val: "ControlRight", display: "", size: 1.25, code: "" },
  ],
];

export default qwertyLayout;
