const qwertyLayout = [
  [
    { val: "`", display: "`", size: 1 },
    { val: "1", display: "1", size: 1 },
    { val: "2", display: "2", size: 1 },
    { val: "3", display: "3", size: 1 },
    { val: "4", display: "4", size: 1 },
    { val: "5", display: "5", size: 1 },
    { val: "6", display: "6", size: 1 },
    { val: "7", display: "7", size: 1 },
    { val: "8", display: "8", size: 1 },
    { val: "9", display: "9", size: 1 },
    { val: "0", display: "0", size: 1 },
    { val: "-", display: "-", size: 1 },
    { val: "=", display: "=", size: 1 },
    { val: "Backspace", display: "Backspace", size: 2 },
  ],
  [
    { val: "Tab", display: "Tab", size: 1.5 },
    { val: "q", display: "Q", size: 1 },
    { val: "w", display: "W", size: 1 },
    { val: "e", display: "E", size: 1 },
    { val: "r", display: "R", size: 1 },
    { val: "t", display: "T", size: 1 },
    { val: "y", display: "Y", size: 1 },
    { val: "u", display: "U", size: 1 },
    { val: "i", display: "I", size: 1 },
    { val: "o", display: "O", size: 1 },
    { val: "p", display: "P", size: 1 },
    { val: "[", display: "[", size: 1 },
    { val: "]", display: "]", size: 1 },
    { val: "\\", display: "\\", size: 1.5 },
  ],
  [
    { val: "CapsLock", display: "Caps", size: 1.75 },
    { val: "a", display: "A", size: 1 },
    { val: "s", display: "S", size: 1 },
    { val: "d", display: "D", size: 1 },
    { val: "f", display: "F", size: 1 },
    { val: "g", display: "G", size: 1 },
    { val: "h", display: "H", size: 1 },
    { val: "j", display: "J", size: 1 },
    { val: "k", display: "K", size: 1 },
    { val: "l", display: "L", size: 1 },
    { val: ";", display: ";", size: 1 },
    { val: "'", display: "'", size: 1 },
    { val: "Enter", display: "Enter", size: 2.25 },
  ],
  [
    { val: "ShiftLeft", display: "Shift", size: 2.25 },
    { val: "z", display: "Z", size: 1 },
    { val: "x", display: "X", size: 1 },
    { val: "c", display: "C", size: 1 },
    { val: "v", display: "V", size: 1 },
    { val: "b", display: "B", size: 1 },
    { val: "n", display: "N", size: 1 },
    { val: "m", display: "M", size: 1 },
    { val: ",", display: ",", size: 1 },
    { val: ".", display: ".", size: 1 },
    { val: "/", display: "/", size: 1 },
    { val: "ShiftRight", display: "Shift", size: 2.75 },
  ],
  [
    { val: "ControlLeft", display: "Ctrl", size: 1.25 },
    { val: "MetaLeft", display: "Win", size: 1.25 },
    { val: "AltLeft", display: "Alt", size: 1.25 },
    { val: " ", display: "Space", size: 6.25 },
    { val: "AltRight", display: "Alt", size: 1.25 },
    { val: "Fn", display: "", size: 1.25 },
    { val: "ContextMenu", display: "Menu", size: 1.25 },
    { val: "ControlRight", display: "Ctrl", size: 1.25 },
  ],
];

export default qwertyLayout;
